name: universal_mqtt_client
description: A MQTT client for Dart, compatible with desktop, mobile and web targets
version: 0.1.1
homepage: https://github.com/soft2tec/universal_mqtt_client
repository: https://github.com/soft2tec/universal_mqtt_client
documentation: https://pub.dev/documentation/universal_mqtt_client/latest/
issue_tracker: https://github.com/soft2tec/universal_mqtt_client/issues

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta: ^1.1.8
  uuid: ^2.1.0
  rxdart: ^0.24.1
  mqtt_client: ^7.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  platform_detect: ^1.4.0
  stream_channel: ^2.0.0
