name: universal_mqtt_client
description: A MQTT client for Dart, compatible with desktop, mobile and web targets
version: 0.1.0
repository: https://github.com/soft2tec/universal_mqtt_client

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta: ^1.1.8
  uuid: ^2.0.4
  rxdart: ^0.23.1
  mqtt_client:
    #path: /mnt/f9/Projects/github.com/shamblett/mqtt_client/
    git:
      url: git://github.com/luca-rand/mqtt_client.git
      ref: d20425161a3f244d7fd59062cae71232f3e46969

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  platform_detect: ^1.4.0
